[tool.ruff]
# Decrease the maximum line length to 79 characters.
line-length = 79

[tool.ruff]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade
]

[tool.ruff.pydocstyle]
convention = "google"