name: Auto Request Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review] # Trigger on new pull requests

jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
      - name: Request review
        uses: necojackarc/auto-request-review@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: "sang-kipkoech"
          
          