name: "auto assign"
on:
  pull_request:
    types: [opened, edited]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        config: '.github/auto-assigner.yml'
        token: ${{ secrets.GITHUB_TOKEN }}