name: Auto Assign Reviewers
on:
  pull_request:
    types:
      - opened

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Assign Reviewers
        uses: actions/github-script@v4
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
