name: 'Auto Assign'
on: pull_request

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: delivery-much/actions-assigner@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: 'sang-kipkoech' # comma-separated list of usernames