name: Releases

on:
    push:
        tags:
            - "v*"
        branches:
            - main
jobs:
    changelog:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: conventional Changelog Action
              id: changelog
              uses: TriPSs/conventional-changelog-action@v3
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: create release
              uses: "marvinpinto/action-automatic-releases@latest"
              if: ${{ steps.changelog.outputs.skipped == 'false'}}
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                prerelease: false
