name: Releases

on:
    push:
        tags:
            - "v*"
        branches:
            - main
jobs:
    changelog:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: create release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                prerelease: false
